In [4]:
import pandas as pd

In [6]:
df = pd.read_csv('/content/datos_seguros.csv', sep=';') # sep=';'
df.head()

,MES_T0,VENTA_SEGURO,NUM_TC_TOTAL_T2,SALDO_BCO_T2,LINEA_BCO_T2,USO_LINEA_BCO_T2,Nro_CTa_Ahorro_Bco_T1,Ahorro_Sldo_Bco_T1,monto_ope_t2,PROM_ANUAL_MTO_OPERA,MAX_MTO_OPERA_Anual,Ratio_HospvsMtoTotal_t2,SEXO,ANTIGUEDAD_MES,DEPARTAMENTO,SOW_BCO_T2,SOW_BCO_SEMESTRAL
0,201506,0,3.0,0.0,2300.0,0.000000,0.0,0.0,15.00,18.644444,52.80,NaN,M,58,LIMA,0.000000,0.000000
1,201506,0,2.0,3215.0,3500.0,0.918571,0.0,0.0,548.98,2632.020000,5709.24,NaN,M,69,JUNIN,0.816134,0.930867
2,201506,0,1.0,3169.0,5000.0,0.633800,0.0,0.0,0.00,4999.000000,4999.00,0.0,M,16,CALLAO,1.000000,1.000000
3,201506,1,1.0,6495.0,8450.0,0.768639,2.0,505.0,2137.94,4900.191666,11206.80,NaN,F,62,LIMA,0.413831,0.505504
4,201506,0,NaN,NaN,NaN,NaN,0.0,0.0,12.37,12.370000,12.37,NaN,F,5,AREQUIPA,0.000000,0.000000

In [ ]:
num_filas, num_columnas = df.shape
print("DataFrame cargado:")
print(df)

In [ ]:
df.info()

In [ ]:
primeras_10_filas = df.head(10)
print("Primeras 10 filas:")
print(primeras_10_filas)

In [ ]:
# Obtener las últimas 10 filas del DataFrame
ultimas_10_filas = df.tail(10)
print("\nÚltimas 10 filas:")
print(ultimas_10_filas)

In [16]:
# Extraer las primeras 1000 filas del DataFrame
primeras_1000_filas = df.head(1000)

# Imprimir las dimensiones del nuevo contenedor
num_filas_nuevo_contenedor, num_columnas_nuevo_contenedor = primeras_1000_filas.shape
print(f"Dimensiones del nuevo contenedor:")
print(f"Número de filas: {num_filas_nuevo_contenedor}")
print(f"Número de columnas: {num_columnas_nuevo_contenedor}")
primeras_1000_filas

Dimensiones del nuevo contenedor:
Número de filas: 1000
Número de columnas: 17

,MES_T0,VENTA_SEGURO,NUM_TC_TOTAL_T2,SALDO_BCO_T2,LINEA_BCO_T2,USO_LINEA_BCO_T2,Nro_CTa_Ahorro_Bco_T1,Ahorro_Sldo_Bco_T1,monto_ope_t2,PROM_ANUAL_MTO_OPERA,MAX_MTO_OPERA_Anual,Ratio_HospvsMtoTotal_t2,SEXO,ANTIGUEDAD_MES,DEPARTAMENTO,SOW_BCO_T2,SOW_BCO_SEMESTRAL
0,201506,0,3.0,0.0,2300.0,0.000000,0.0,0.0,15.00,18.644444,52.80,NaN,M,58,LIMA,0.000000,0.000000
1,201506,0,2.0,3215.0,3500.0,0.918571,0.0,0.0,548.98,2632.020000,5709.24,NaN,M,69,JUNIN,0.816134,0.930867
2,201506,0,1.0,3169.0,5000.0,0.633800,0.0,0.0,0.00,4999.000000,4999.00,0.000000,M,16,CALLAO,1.000000,1.000000
3,201506,1,1.0,6495.0,8450.0,0.768639,2.0,505.0,2137.94,4900.191666,11206.80,NaN,F,62,LIMA,0.413831,0.505504
4,201506,0,NaN,NaN,NaN,NaN,0.0,0.0,12.37,12.370000,12.37,NaN,F,5,AREQUIPA,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,201506,0,1.0,4357.0,4600.0,0.947173,0.0,0.0,187.58,758.380833,1326.14,NaN,M,25,LIMA,0.194025,0.180906
996,201506,0,NaN,NaN,NaN,NaN,1.0,545.0,104.00,104.000000,104.00,1.000000,F,55,CUSCO,0.000000,0.000000
997,201506,0,NaN,NaN,NaN,NaN,0.0,0.0,414.64,243.107500,550.00,NaN,F,24,LIMA,1.000000,1.000000
998,201506,0,1.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,0.000000,M,50,AREQUIPA,0.000000,0.000000
999,201506,0,4.0,0.0,0.0,0.000000,2.0,436.0,108.52,166.578333,626.52,0.202727,M,94,LA LIBERTAD,0.000000,0.000000