In [ ]:
#Generando el Data Frame con Pandas
import pandas as pd

data = {
    'Mes': ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo'],
    'Ventas': [30500, 35600, 28300, 33900, 42500],
    'Gastos': [22000, 23450, 18100, 35700, 32450]
}

df1 = pd.DataFrame(data)

df1

In [10]:
#Generar la Columna1 dónde se muestre el % del gasto con las ventas
df1['% Gastos'] = (df1['Gastos']/df1['Ventas'])*100
df1['Meta'] = df1['Ventas'].apply(lambda x: 'Meta Superada' if x >= 30000 else 'Meta no Superada')
df1['Sobre Gastos'] = df1.apply(lambda row: row['Gastos'] - row['Ventas'] if row['Gastos'] > row['Ventas'] else "Sin sobre Gastos", axis=1)
df1

       Mes  Ventas  Gastos    % Gastos              Meta      Sobre Gastos
0    Enero   30500   22000   72.131148     Meta Superada  Sin sobre Gastos
1  Febrero   35600   23450   65.870787     Meta Superada  Sin sobre Gastos
2    Marzo   28300   18100   63.957597  Meta no Superada  Sin sobre Gastos
3    Abril   33900   35700  105.309735     Meta Superada              1800
4     Mayo   42500   32450   76.352941     Meta Superada  Sin sobre Gastos

In [14]:
total_ult_3_meses = df1['Ventas'][-3:].sum()
print("Total de Ventas de los últimos 3 meses:", total_ult_3_meses)

Total de Ventas de los últimos 3 meses: 104700

In [20]:
# Crearemos un diccionario para asignar un valor numérico a cada mes, luego utilizaremos .map() para volver los nombres en valor númerico,
# y que de esta manera podamos utilizar los meses entre febrero y Abril.
meses_numericos = {
    'Enero': 1,
    'Febrero': 2,
    'Marzo': 3,
    'Abril': 4,
    'Mayo': 5
}

# Filtrar las filas del DataFrame para los meses de 'Febrero' a 'Abril'
gastos_feb_abr = df1[(df1['Mes'].map(meses_numericos) >= meses_numericos['Febrero']) & (df1['Mes'].map(meses_numericos) <= meses_numericos['Abril'])]

# Calcular el total de los 'Gastos' en esas filas
total_gastos_feb_abr = gastos_feb_abr['Gastos'].sum()

print("Total de Gastos de los meses de Febrero a Abril:", total_gastos_feb_abr)

Total de Gastos de los meses de Febrero a Abril: 77250